### 회원가입 요청
POST localhost:8080/api/v1/members
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "ratel0801!"
}


### 로그인 요청
POST localhost:8080/api/v1/members/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "ratel0801!"
}


### 시큐리티 테스트
GET localhost:8080/api/v1/products/test
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QHRlc3QuY29tIiwiYXV0aCI6IlJPTEVfVVNFUiIsInR5cGUiOiJBQ0NFU1MiLCJpZCI6MSwiaWF0IjoxNzM1Nzc3MTIzLCJleHAiOjE3MzU3ODA3MjN9.rAlftASjdGz1-31uiBv9NnY82fhdjjX0JP1z-P0Cpzo


