### 회원가입 요청
POST localhost:8080/api/v1/members
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "ratel0801!"
}


### 로그인 요청
POST localhost:8080/api/v1/members/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "ratel0801!"
}


### 시큐리티 테스트
GET localhost:8080/api/v1/members/test
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QHRlc3QuY29tIiwiYXV0aCI6IlJPTEVfVVNFUiIsInR5cGUiOiJBQ0NFU1MiLCJpZCI6MSwiaWF0IjoxNzM1NjA1MzcxLCJleHAiOjE3MzU2MDg5NzF9.m3jguifvOeoLjcLkgD5rT_nMa396Lwg2IpimmSfC3is


